project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl
description-meta: "R para Análisis estadístico"

website:
  title: "R para Análisis estadístico"
  site-url: "https://R-analisis-datos.netlify.app"
  description: "Departamento de Sociología de la Universidad Alberto"
  favicon: "/files/icon-512.png"

  twitter-card:
    image: "/files/social-image-sp23.png"
    card-style: summary_large_image
    creator: "@KevinCarrascoQ1"
    # site: "@andrewheiss"

  open-graph:
    image: "/files/social-image-sp23.png"
    locale: en_US

  navbar:
    pinned: true
    background: "#093b69"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Clases"
        file: content/index.qmd
      - text: "Prácticos"
        file: practicos/index.qmd
      - text: "Herramientas"
        file: herramientas/index.qmd
      - text: "Trabajos"
        file: assignment/index.qmd
#      - text: "News"
#        file: news/index.qmd
#      - icon: slack
#        href: "https://gsuevalsp2023.slack.com"
#        aria-label: Slack
      - icon: cloud-fill
        href: "https://rstudio.cloud"
        aria-label: RStudio.cloud

  sidebar:

    - title: "Clases"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Información general"
          contents:
            - content/index.qmd
        - section: "Clases"
          contents:
            - text: "01: Clase 1"
              file: content/01-content.qmd
            - text: "02: Clase 2"
              file: content/02-content.qmd
            - text: "03: Clase 3"
              file: content/03-content.qmd
            - text: "04: Clase 4"
              file: content/04-content.qmd
            - text: "05: Clase 5"
              file: content/05-content.qmd
            - text: "06: Clase 6"
              file: content/06-content.qmd
            - text: "07: Clase 7"
              file: content/07-content.qmd

    - title: "Prácticos"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Información general"
          contents:
            - practicos/index.qmd
        - section: "Talleres"
          contents:
            - text: "01: Práctico 1"
              file: practicos/01-content.qmd
            - text: "02: Práctico 2"
              file: practicos/02-content.qmd
            - text: "03: Práctico 3"
              file: practicos/03-content.qmd
            - text: "04: Práctico 4"
              file: practicos/04-content.qmd
            - text: "05: Práctico 5"
              file: practicos/05-content.qmd
            - text: "06: Práctico 6"
              file: practicos/06-content.qmd
            - text: "07: Práctico 7"
              file: practicos/07-content.qmd
            - text: "08: Resumen"
              file: practicos/resumen-content.qmd
            - text: "09: Práctico 8"
              file: practicos/08-content.qmd

    - title: "Herramientas"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Información general"
          contents:
            - herramientas/index.qmd
        - section: "Herramientas"
          contents:
            - text: "Github"
              file: herramientas/01-content.qmd

    - title: "Trabajos"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Información general"
          contents:
            - assignment/index.qmd
        - section: "Trabajos"
          contents:
            - text: "Trabajo 1"
              file: assignment/01-trabajo.qmd
            - text: "Trabajo 2"
              file: assignment/02-trabajo.qmd
            - text: "Trabajo 3"
              file: assignment/03-trabajo.qmd


  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by Kevin Carrasco <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
