project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!slides/"
  resources:
    - "files/"
    - "projects/"
    - "slides/*.html"
    - "slides/*.pdf"
    - "slides/img/"
    - "slides/libs/"
    - "slides/css/"
    - "slides/*_files/"

# See https://quarto.org/docs/projects/code-execution.html#freeze
execute:
  freeze: auto  # Re-render only when source changes

bibliography: files/bib/references.bib
csl: files/bib/chicago-author-date.csl
description-meta: "Estrategias de investigación cuantitativa"

website:
  title: "Estrategias de investigación cuantitativa"
  site-url: "https://investigacion-cuantitativa.netlify.app"
  description: "Carrera de Sociología de la Facultad de Ciencias Sociales de la Universidad de Chile"
  favicon: "/files/icon-512.png"

  twitter-card:
    image: "/files/social-image-sp23.png"
    card-style: summary_large_image
    creator: "@KevinCarrascoQ1"
    # site: "@andrewheiss"

  open-graph:
    image: "/files/social-image-sp23.png"
    locale: en_US

  navbar:
    pinned: true
    background: "#27cf1b"
    right:
      - syllabus.qmd
      - schedule.qmd
      - text: "Contenidos"
        file: content/index.qmd
      - text: "Talleres"
        file: assignment/index.qmd
      - text: "Prácticos R"
        file: practicos/index.qmd
      - trabajos.qmd
#      - text: "News"
#        file: news/index.qmd
#      - icon: slack
#        href: "https://gsuevalsp2023.slack.com"
#        aria-label: Slack
      - icon: cloud-fill
        href: "https://rstudio.cloud"
        aria-label: RStudio.cloud

  sidebar:
    - title: "Contenidos"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Información general"
          contents:
            - content/index.qmd
        - section: "Sesiones"
          contents:
            - text: "01: Sesión 1"
              file: content/01-content.qmd

    - title: "Talleres"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Información general"
          contents:
            - assignment/index.qmd
        - section: "Talleres"
          contents:
            - text: "01: Taller 1"
              file: talleres/01-taller.qmd

    - title: "Prácticos R"
      style: "docked"
      search: false
      background: dark
      contents:
        - section: "Información general"
          contents:
            - practicos/index.qmd
        - section: "Prácitocs R"
          contents:
            - text: "01: Práctico 1"
              file: practico/01-content.qmd


  page-footer:
    left: |
      Content {{< fa brands creative-commons >}} {{< var course.copyright_year >}} by [{{< var instructor.name_no_title >}}]({{< var instructor.url >}}) <br>
      All content licensed under a {{< fa brands creative-commons >}}
      {{< fa brands creative-commons-by >}} {{< fa brands creative-commons-nc >}}
      [Creative Commons Attribution-NonCommercial 4.0 International license (CC BY-NC 4.0)](https://creativecommons.org/licenses/by-nc/4.0/)
    right: |
      Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)<br>
      [View the source at {{< fa brands github >}} GitHub]({{< var course.github >}})

format:
  html:
    theme:
      - litera
      - html/custom.scss
    toc: true
    highlight-style: monokai
